language: node_js
node_js:
  - '7.7.1'

before_install:
  - npm install -g webpack

script:
  - npm run build

deploy:
  provider: npm
  email: sandbox_JSUI@coveo.com
  skip_cleanup: true
  api_key:
    secure: gUvnqDJWS8bncjiPmm6uIO1j5juE02dV/b96z5CONe4KW8CuTkgIRPNdVfUUfkfKwII3RThxr1R5D2lNaUvZS/cEcCbKFUXuDSpucp1m5kt0Qu1L4aGAlPiAe9pB/zPl08YWw41sQi3UantgZ/BqVp0Vbh1G+awtCHq4U+XgQKny2hY3W21x+JEVCJwDH16yVWKaB84yl6yPPjzUoa4QlR580cXisLA3wg7dWZ7JdLOuE6VU//dLKkbey9nY0VY9jyVtxlzpx6aoM1mVwrGZOB1kI2oeC/jDbUkMs4KQW3LU/gUDSFUH8vA7ey6lh9Re9tf0RiUqIMAXSQROIeHfhHsLxoCEnoN+s1kXj5Qe6eja8nSMYqTvhqgeqC3LSe2e2jNAbHsv4ZjT0JBJefmktMr2P70QamC6nzNOAuzO/skZSHQ5eM1E/g/dEed4RAVud0upqucxC8DJo6mDrEp9hcLf399KJZwNbEeTpARfcVLde5oKglQSbhHDuHzrCb+jNLs924cQq5Y8UC5T7NhPd+tMEDo8W14fFCTxQm0Z4bh9uKnSZO8ut4bvgf86i9MExdptfENXDkMRjT/p5TckVNvhY4Vd8ucvSfwTLc0dX/hABFEp9VNenzYHlVq4QE+J1KBLn9jzPKkS60j7Orydotf1yfI+eB3jjSgqEUBpLiE=
  on:
    tags: true